plugin:
  - any:
      - changed-files:
          - any-glob-to-any-file: ['packages/plugin/**']

swc:
  - any:
      - changed-files:
          - any-glob-to-any-file: ['packages/swc/**']

core:
  - any:
      - changed-files:
          - any-glob-to-any-file: ['packages/core/**']
