name: 'Pull Request Labeler'

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - uses: actions/labeler@v6
